FROM fedora:latest
RUN dnf -y update && dnf -y upgrade
RUN dnf -y install vim

RUN yum -y install curl cvs subversion make autoconf gcc gcc-c++ automake bzip2
RUN yum -y install bitstream-vera-sans-mono-fonts tcl tcl-devel tk tk-devel jack-audio-connection-kit jack-audio-connection-kit-devel alsa-lib alsa-lib-devel libtool
